### ISSUE TITLE
hello,看到了你腾讯云上的文章，但现在万象优图又有了新的变化，所以有些问题

### ISSUE THREAD

**Issue by bug0error** [sixtrees/MagicImage#1]
现在在保存APP_ID等信息时就会出错，而且万象优图的UI也变了

**Comment by edocevol** [comment]
@RoyCao1995 新版本会解决。

**Comment by edocevol** [comment]
@RoyCao1995 你好，我检查了一下，可以保存APPID的。
万象有图现在全部转移到对象存储了，地址为：https://console.cloud.tencent.com/cos
